title: Ellaism Wiki
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
markdown: kramdown
destination: "docs"
baseurl: "/wiki"
base_url: "/wiki"
tipue_search:
  include:
    pages: true
  exclude:
    files: []
